import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sections/navbar";
import { albraBold } from "./fonts";
import { LandingPageProvider } from "@/context/LandingPageContext";
import Footer from "@/components/sections/Footer.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={albraBold.variable}>
      <body
        className={`
          
          ${lato.className}

          antialiased
        `}
      >
        <LandingPageProvider>
          <Navbar />
          {children}
          <Footer />
        </LandingPageProvider>
      </body>
    </html>
  );
}
