import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sections/navbar";
import { primaryFont } from "./fonts";
import { LandingPageProvider } from "@/context/LandingPageContext";
import { Footer } from "@/components/sections/Footer.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${primaryFont.variable}
          antialiased
        `}
      >
        <LandingPageProvider>
          <Navbar />
          {children}
          <Footer/>
        </LandingPageProvider>
      </body>
    </html>
  );
}
